### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by tsroten** [hermanschaaf/mafan#9]
Currently mafan only supports Python 2 (not sure which versions). mafan's dependencies (jieba and jianfan) don't offer Python 3 support yet. jieba has jieba3k, however, it is a fork and isn't incorporated into jieba's master branch. I already submitted a Python 2 and 3 compatible version of jianfan to its developer.

Even though jieba doesn't support Python 3 yet, I think it would be good for mafan to be ready for it.

A first step could be using only unicode strings internally via adding:
`from __future__ import unicode_literals`
to every module and dropping all 'u' prefixes from strings.

@hermanschaaf What do you think?

**Comment by lucaskjaero** [comment]
Is this still in progress? If so, how can I assist?

**Comment by tsroten** [comment]
@lucaskjaero Despite volunteering to help with this, I never made any progress. It was just one of those things that got added to my list, but never looked at again. You might see if @hermanschaaf has any news on this.

**Comment by hermanschaaf** [comment]
@lucaskjaero @tsroten I don't have any news on this :) But if someone wants to put some time into it, a pull request is welcome, I'll be sure to get it merged. Otherwise, it is something I can put on my personal backlog this month.

**Comment by lucaskjaero** [comment]
I'll take a crack at it!

**Comment by hermanschaaf** [comment]
Finally this was fixed by https://github.com/hermanschaaf/mafan/pull/17 and the pypi version updated. Let me know if you run into any issues!
